### ISSUE TITLE
Domain Events

### ISSUE THREAD

**Issue by wesnick** [buttercup-php/protects#1]
I like that this library provides a very basic contract for event sourcing, without too much concrete implementation.  

Where is the most appropriate place is to dispatch domain events?  Before commit? Before apply?  How to deal with replays and events?

**Comment by mathiasverraes** [comment]
There are different styles. My preference is to use the `RecordsEvents::getRecordedEvents()`, then commit these events to the event store, and when they are confirmed, have the event store hand them over to an EventPublisher. This provides great safety (if the commit fails, no listeners will be notified), and it keeps event dispatching out of the aggregate's responsibilities.

Event storage and publishing are out of scope for Buttercup.Protects, but I hope to find some time soon to extract libraries from my production code for that as well.

**Comment by wesnick** [comment]
Thanks for the comments.
