### ISSUE TITLE
Trait for recording events

### ISSUE THREAD

**Issue by adamquaile** [buttercup-php/protects#7]
Would you consider a trait like this to reduce boilerplate code in aggregates? Not sure that it would be suited to every use-case, but could certainly be useful..?

```
trait CanRecordEvents
{
    /**
     * @var DomainEvent[]
     */
    private $latestRecordedEvents = [];

    private function recordThat(DomainEvent $event)
    {
        $this->latestRecordedEvents[] = $event;
    }

    /**
     * @return DomainEvents
     */
    public function getRecordedEvents()
    {
        return new DomainEvents($this->latestRecordedEvents);
    }

    public function clearRecordedEvents()
    {
        $this->latestRecordedEvents = [];
    }
}
```

**Comment by mathiasverraes** [comment]
I'm not really working on Buttercup anymore. It was a fun experiment, and it's great as an educational tool, but the idea of only providing interfaces is not really viable in php. http://github.com/event-centric is where it's all happening now :)

**Comment by adamquaile** [comment]
Yeah, I have been slowly adding my own implementation to it, as it seemed like a set of sensible interfaces.

Looks like that's the wheel I was looking for instead of reinventing :)

Thanks
